name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Base Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          sudo apt-get install -y autoconf automake libtool libtool-bin libltdl-dev pkg-config cmake gettext libffi-dev libssl-dev
          pip install --user --upgrade Cython==0.29.33 buildozer

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Force clean build to clear old broken welds
          buildozer android clean
          yes | buildozer -v android debug
          
      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: Foreman-App-Package
          path: bin/*.apk
