name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build with Buildozer
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: master
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Foreman-App-${{ steps.get-date.outputs.date }}
          path: bin/*.apk

